name: Deploy to AWS EC2

on:
  push:
    paths:
      - 'server/**'
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20.12.0'

      - name: Install dependencies
        run: |
          cd server
          npm set legacy-peer-deps true
          npm install

      - name: Build production
        run: |
          cd server
          npm run build:prod

      - name: Transfer build folder via SSH
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: 'server/build/**'
          target: '~/Daily-Bible/server/build'

      - name: Execute remote commands via SSH
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/Daily-Bible/server
            npm install --omit=dev
            pm2 start build/server.js
            pm2 save
