name: Deploy to EC2 PROD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/bibleKey.pem
          chmod 600 ~/.ssh/bibleKey.pem

      - name: Deploy to EC2
        env:
          SSH_KEY: ${{ secrets.EC2_SSH_KEY }}
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/bibleKey.pem ubuntu@ec2-13-50-7-79.eu-north-1.compute.amazonaws.com << 'EOF'
            cd Daily-Bible/server
            npm set legacy-peer-deps true
            npm install
            npm run build:prod
            pm2 startOrRestart ecosystem.config.js --only server
          EOF
