name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    container: pandoc/latex
    steps:
      - uses: actions/checkout@v2
      - name: Set random username
        id: set_username
        shell: sh
        run: |
          USERNAMES="avichai997 ahuvia uria"
          set -- $USERNAMES
          RANDOM_USERNAME=$(eval echo \${$((RANDOM % $# + 1))})
          echo "RANDOM_USERNAME=$RANDOM_USERNAME" >> $GITHUB_ENV
      - name: Pushes to another repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@target-branch
        env:
          API_TOKEN_GITHUB: ${{ secrets.GIT_ACCESS_TOKEN }}
        with:
          source-directory: .
          destination-repository-username: 'Avichai997'
          destination-repository-name: 'DailyBible-Fullstack-course'
          user-email: avichai997@gmail.com
          destination-github-username: ${{ env.RANDOM_USERNAME }}
          commit-message: See ORIGIN_COMMIT from $GITHUB_REF
          target-branch: main
      - name: Test get variable exported by push-to-another-repository
        run: echo $DESTINATION_CLONED_DIRECTORY
